[[redirects]]
  from = "https://matteomanzinello.com/tiamo"
  to = "https://ilariaberetta.com"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "https://matteomanzinello.com"
  status = 301
  force = true