[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "https://matteomanzinello.netlify.com/*"
  to = "https://matteomanzinello.com/:splat"
  status = 301
  force = true